2022/08/16 05:38:26 deprecation_wrapper.py[line:119] WARNING: From /data/yin-group/models/adv-dnn-ens/adv-dnn-ens-malware/learner/basic_DNN.py:204: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

2022/08/16 05:38:27 deprecation_wrapper.py[line:119] WARNING: From /data/yin-group/models/adv-dnn-ens/adv-dnn-ens-malware/defender/d_ade_ma.py:145: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

2022/08/16 05:38:27 deprecation.py[line:506] WARNING: From /data/yin-group/models/adv-dnn-ens/adv-dnn-ens-malware/defender/d_ade_ma.py:150: calling Constant.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
2022/08/16 05:38:27 deprecation_wrapper.py[line:119] WARNING: From /data/yin-group/models/adv-dnn-ens/adv-dnn-ens-malware/defender/d_ade_ma.py:151: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

2022/08/16 05:38:27 deprecation_wrapper.py[line:119] WARNING: From /data/yin-group/models/adv-dnn-ens/adv-dnn-ens-malware/defender/d_ade_ma.py:152: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

2022/08/16 05:38:27 deprecation.py[line:323] WARNING: From /data/yin-group/models/adv-dnn-ens/adv-dnn-ens-malware/learner/basic_DNN.py:62: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dense instead.
2022/08/16 05:38:27 deprecation.py[line:506] WARNING: From /data/yin-group/yin-group/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
2022/08/16 05:38:27 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed800fbc18>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed800fbc18>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:27 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee13349a90>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee13349a90>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:27 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee13349a90>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee13349a90>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:27 deprecation.py[line:323] WARNING: From /data/yin-group/models/adv-dnn-ens/adv-dnn-ens-malware/defender/at.py:179: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
2022/08/16 05:38:27 deprecation_wrapper.py[line:119] WARNING: From /data/yin-group/models/adv-dnn-ens/adv-dnn-ens-malware/defender/at.py:187: The name tf.assign is deprecated. Please use tf.compat.v1.assign instead.

2022/08/16 05:38:28 lazy_loader.py[line:50] WARNING: 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

2022/08/16 05:38:28 deprecation.py[line:323] WARNING: From /data/yin-group/models/adv-dnn-ens/adv-dnn-ens-malware/attacker/methods/pgd_adam.py:62: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
2022/08/16 05:38:28 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fa497b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fa497b8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:28 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fa497b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fa497b8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:28 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fa497b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fa497b8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:28 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed8013be80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed8013be80>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:28 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed8013be80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed8013be80>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:28 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed8013be80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed8013be80>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:28 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fc96d68>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fc96d68>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:28 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fc96d68>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fc96d68>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:28 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fc96d68>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fc96d68>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:28 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fa86cc0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fa86cc0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:28 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fa86cc0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fa86cc0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:28 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fa86cc0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fa86cc0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:28 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ebee2b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ebee2b0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:28 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ebee2b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ebee2b0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:28 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ebee2b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ebee2b0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:28 deprecation_wrapper.py[line:119] WARNING: From /data/yin-group/models/adv-dnn-ens/adv-dnn-ens-malware/attacker/methods/pgdl1.py:98: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

2022/08/16 05:38:28 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fad78d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fad78d0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:28 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fad78d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fad78d0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:28 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fad78d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fad78d0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:28 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7eaa13c8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7eaa13c8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:28 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7eaa13c8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7eaa13c8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:28 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7eaa13c8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7eaa13c8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:28 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7eb7eeb8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7eb7eeb8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:28 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7eb7eeb8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7eb7eeb8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:28 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7eb7eeb8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7eb7eeb8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:28 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ea2ecf8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ea2ecf8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:28 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7eaaca20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7eaaca20>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:28 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7eaaca20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7eaaca20>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ec037b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ec037b8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ec037b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ec037b8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ec037b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ec037b8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7edbeeb8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7edbeeb8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4ee7f160>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4ee7f160>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4ee7f160>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4ee7f160>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ea65198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ea65198>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ea65198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ea65198>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ea65198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ea65198>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c820898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c820898>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c820898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c820898>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c820898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c820898>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c8a9cf8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c8a9cf8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c8a9cf8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c8a9cf8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c8a9cf8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c8a9cf8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c74cdd8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c74cdd8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c74cdd8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c74cdd8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c74cdd8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c74cdd8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c878908>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c878908>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c878908>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c878908>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c878908>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c878908>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c724b70>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c724b70>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c724b70>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c724b70>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c724b70>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c724b70>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c775dd8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c775dd8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c72ea58>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c72ea58>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c7c7978>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c7c7978>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c724b70>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c724b70>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c724b70>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c724b70>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c724b70>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c724b70>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c775940>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c775940>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c878908>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c878908>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c878908>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c878908>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c724b70>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c724b70>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c724b70>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c724b70>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c724b70>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c724b70>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4a0024a8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4a0024a8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4a0024a8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4a0024a8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4a0024a8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4a0024a8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee49fa45c0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee49fa45c0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c72ef60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c72ef60>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c72ef60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c72ef60>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c6b0128>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c6b0128>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4a002588>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4a002588>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4a002588>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4a002588>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:29 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4a002748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4a002748>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c700c88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c700c88>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4a002748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4a002748>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c6b0a90>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c6b0a90>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c700a58>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c700a58>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c6b0a90>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c6b0a90>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c6c2e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c6c2e48>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c6c2e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c6c2e48>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c6c2e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c6c2e48>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c679a58>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c679a58>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c679a58>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c679a58>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c679a58>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c679a58>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c6c2e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c6c2e48>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c6c2e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c6c2e48>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c6c2e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c6c2e48>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c679a58>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c679a58>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c679a58>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c679a58>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c679a58>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4c679a58>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7f928400>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7f928400>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7f928400>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7f928400>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7f928400>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7f928400>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee46fe6b38>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee46fe6b38>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee46fe6b38>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee46fe6b38>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee46f84860>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee46f84860>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee46fe6a90>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee46fe6a90>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee49fb55f8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee49fb55f8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee46f84828>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee46f84828>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee46fe6d30>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee46fe6d30>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee49fb55f8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee49fb55f8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee49fb55f8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee49fb55f8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee49fb5b38>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee49fb5b38>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee46f84fd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee46f84fd0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee49fb5550>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee49fb5550>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee470012b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee470012b0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee46fe6b38>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee46fe6b38>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:30 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee46fe6b38>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee46fe6b38>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:31 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee447c6be0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee447c6be0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:31 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee447c6be0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee447c6be0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:31 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee447c6be0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee447c6be0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:31 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee447d49e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee447d49e8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:31 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee447d49e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee447d49e8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:31 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee447d49e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee447d49e8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:31 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee447d49e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee447d49e8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:31 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee447d49e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee447d49e8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:31 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee447d49e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee447d49e8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:31 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee447c6c50>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee447c6c50>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:31 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee46f96160>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee46f96160>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:31 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee46fa85f8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee46fa85f8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:31 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee447d49b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee447d49b0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:31 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee447d49b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee447d49b0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:31 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee447d49b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee447d49b0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:31 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee400449b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee400449b0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:31 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee400449b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee400449b0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:31 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee400449b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee400449b0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee40044a20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee40044a20>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee40044a20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee40044a20>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee40044a20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee40044a20>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee40044ef0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee40044ef0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3ffd5e80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3ffd5e80>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee40044ef0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee40044ef0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee400449e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee400449e8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee400449e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee400449e8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee400449e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee400449e8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee40044ba8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee40044ba8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee40044ba8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee40044ba8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee40044ba8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee40044ba8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3fe6de80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3fe6de80>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3fe6de80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3fe6de80>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3fe6de80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3fe6de80>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4701b550>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4701b550>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4701b550>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4701b550>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4701b550>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4701b550>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3fe7d588>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3fe7d588>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db017f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db017f0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3ffefc18>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3ffefc18>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3fe6de80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3fe6de80>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3fe6de80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3fe6de80>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3fe6de80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3fe6de80>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4701b550>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee4701b550>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db01f60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db01f60>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db01f60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db01f60>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db18be0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db18be0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db1ce48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db1ce48>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db18be0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db18be0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db1c6a0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db1c6a0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db18be0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db18be0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db1c6a0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db1c6a0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db18be0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db18be0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db1c6a0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db1c6a0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db1c6a0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db1c6a0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db35860>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db35860>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db1c710>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db1c710>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db35860>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db35860>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db1c128>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db1c128>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db35320>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db35320>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db1c128>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3db1c128>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3daf5b00>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3daf5b00>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3daf5b00>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3daf5b00>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3daf5b00>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3daf5b00>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3dab9c50>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3dab9c50>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3da465f8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3da465f8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3dab9c50>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3dab9c50>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3daf5b00>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3daf5b00>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3daf5b00>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3daf5b00>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3daf5b00>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3daf5b00>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3da466a0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3da466a0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:32 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3dab9c50>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3dab9c50>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:33 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3dab9c50>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3dab9c50>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:33 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3daf52b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3daf52b0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:33 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3daf52b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3daf52b0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:33 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3daf52b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fee3daf52b0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7f984ef0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7f984ef0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7f984ef0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7f984ef0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7f984ef0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7f984ef0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7f965e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7f965e48>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7f965e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7f965e48>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7f965e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7f965e48>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fc2db70>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fc2db70>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fc2db70>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fc2db70>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fc2db70>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fc2db70>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7f984ef0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7f984ef0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7f984ef0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7f984ef0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7f984ef0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7f984ef0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fc76b38>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fc76b38>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fc76b38>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fc76b38>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fc76b38>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fc76b38>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fc207f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fc207f0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fc207f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fc207f0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fc207f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fc207f0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fddbcf8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fddbcf8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fddbcf8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fddbcf8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fddbcf8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fddbcf8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fa7b278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fa7b278>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fa7b278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fa7b278>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fa7b278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fa7b278>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fbf8b70>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fbf8b70>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fbf8b70>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fbf8b70>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fbf8b70>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fbf8b70>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed80058ef0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed80058ef0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed80058ef0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed80058ef0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed80058ef0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed80058ef0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ffce9b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ffce9b0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ffce9b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ffce9b0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ffce9b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ffce9b0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fbf8b70>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fbf8b70>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fbf8b70>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fbf8b70>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:34 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fbf8b70>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fbf8b70>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:35 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed801b7f60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed801b7f60>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:35 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed801b7f60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed801b7f60>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:35 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed801b7f60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed801b7f60>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:35 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ffce9b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ffce9b0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:35 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ffce9b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ffce9b0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:35 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ffce9b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ffce9b0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:35 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fddbcf8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fddbcf8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:35 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fddbcf8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fddbcf8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:35 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fddbcf8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fddbcf8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:35 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed806e91d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed806e91d0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:35 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed806e91d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed806e91d0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:35 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed806e91d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed806e91d0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:35 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fddbcf8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fddbcf8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:35 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fddbcf8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fddbcf8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:35 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fddbcf8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7fddbcf8>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:35 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ffce9b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ffce9b0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:35 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ffce9b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ffce9b0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:35 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ffce9b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed7ffce9b0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:35 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed806e91d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed806e91d0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:35 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed806e91d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed806e91d0>>: AttributeError: module 'gast' has no attribute 'Index'
2022/08/16 05:38:35 ag_logging.py[line:145] WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed806e91d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7fed806e91d0>>: AttributeError: module 'gast' has no attribute 'Index'
